services:
    quantum-jupyter:
        image: quantum-jupyter
        hostname: quantum-jupyter
        container_name: quantum-jupyter
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./code:/home/jovyan/code
            - ./examples:/home/jovyan/examples
        ports:
            - 8888:8888
        command: "start-notebook.sh --NotebookApp.token="
